# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_App(object):
    def setupUi(self, App):
        App.setObjectName("App")
        App.resize(900, 500)
        self.verticalLayout = QtWidgets.QVBoxLayout(App)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=App)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.txtCCCD = QtWidgets.QLineEdit(parent=App)
        self.txtCCCD.setObjectName("txtCCCD")
        self.verticalLayout.addWidget(self.txtCCCD)
        self.label_2 = QtWidgets.QLabel(parent=App)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.txtHoTen = QtWidgets.QLineEdit(parent=App)
        self.txtHoTen.setObjectName("txtHoTen")
        self.verticalLayout.addWidget(self.txtHoTen)
        self.label_3 = QtWidgets.QLabel(parent=App)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.dateNS = QtWidgets.QDateEdit(parent=App)
        self.dateNS.setObjectName("dateNS")
        self.verticalLayout.addWidget(self.dateNS)
        self.label_4 = QtWidgets.QLabel(parent=App)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.cbGT = QtWidgets.QComboBox(parent=App)
        self.cbGT.setObjectName("cbGT")
        self.verticalLayout.addWidget(self.cbGT)
        self.label_5 = QtWidgets.QLabel(parent=App)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.txtDiaChi = QtWidgets.QLineEdit(parent=App)
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.verticalLayout.addWidget(self.txtDiaChi)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnThem = QtWidgets.QPushButton(parent=App)
        self.btnThem.setObjectName("btnThem")
        self.horizontalLayout.addWidget(self.btnThem)
        self.btnSua = QtWidgets.QPushButton(parent=App)
        self.btnSua.setObjectName("btnSua")
        self.horizontalLayout.addWidget(self.btnSua)
        self.btnXoa = QtWidgets.QPushButton(parent=App)
        self.btnXoa.setObjectName("btnXoa")
        self.horizontalLayout.addWidget(self.btnXoa)
        self.btnTim = QtWidgets.QPushButton(parent=App)
        self.btnTim.setObjectName("btnTim")
        self.horizontalLayout.addWidget(self.btnTim)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.txtTim = QtWidgets.QLineEdit(parent=App)
        self.txtTim.setObjectName("txtTim")
        self.verticalLayout.addWidget(self.txtTim)
        self.table = QtWidgets.QTableWidget(parent=App)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        self.table.setRowCount(0)
        self.verticalLayout.addWidget(self.table)

        self.retranslateUi(App)
        QtCore.QMetaObject.connectSlotsByName(App)

    def retranslateUi(self, App):
        _translate = QtCore.QCoreApplication.translate
        App.setWindowTitle(_translate("App", "Quản lý nhân sự (SQL Server)"))
        self.label.setText(_translate("App", "CCCD"))
        self.label_2.setText(_translate("App", "Họ tên"))
        self.label_3.setText(_translate("App", "Ngày sinh"))
        self.label_4.setText(_translate("App", "Giới tính"))
        self.label_5.setText(_translate("App", "Địa chỉ"))
        self.btnThem.setText(_translate("App", "Thêm"))
        self.btnSua.setText(_translate("App", "Sửa"))
        self.btnXoa.setText(_translate("App", "Xóa"))
        self.btnTim.setText(_translate("App", "Tìm"))
        self.txtTim.setPlaceholderText(_translate("App", "Nhập CCCD / tên / địa chỉ..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    App = QtWidgets.QWidget()
    ui = Ui_App()
    ui.setupUi(App)
    App.show()
    sys.exit(app.exec())
